const me ={ 
age: 24,
heigh: 168,
hobby: 'Reading',
favoriteColor: 'black',
favoriteAnimal: 'cat',
education: 'LNMU',
work: 'QA',
country: 'Ukraine',
city: 'Lviv',
adress: 'Zolota Street',
favoriteFood: 'pizza',
favoriteMovie: 'Titanic',
name: 'Julia',
surname: 'Chmelyk',
speakingLanguage: 'Ukrainian',
eyeColor: 'grey',
favoriteDrink: 'Coffee',
favoriteBook: 'Bukvar',
favoriteShoes: 'Sneakers',
favoriteClothes: 'jeans'
}